name: Quality

on:
  push:
    branches: [ main, develop ]

jobs:
  analyze:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      # uses: SonarSource/sonarcloud-github-action@f4c6e4d91ea9785ec823eaeed459042606123402
      uses: SonarSource/sonarcloud-github-action@v1.4
      with:
        args: >
          -Dsonar.organization=cboiam
          -Dsonar.projectKey=cboiam_ImplementationDiscovery
          -Dsonar.cs.vstest.reportsPaths=./TestResults/**.trx  
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
